# framework:
#     default_locale: '%locale%'
#     translator:
#         paths:
#             - '%kernel.project_dir%/translations'
#         fallbacks:
#             - '%locale%'
framework:
    default_locale: 'fr'
    translator:
        paths:
            - '%kernel.project_dir%/translations'
        fallbacks:
            - 'en'
